// <auto-generated />
using BlazorBolos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBolos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240528021252_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorBolos.Data.Bolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Bolos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Bolo de banana",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_banana.jpg",
                            Nome = "Bolo de banana",
                            Preco = 23.00m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Bolo brigadeiro",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_brigadeiro.jpg",
                            Nome = "Bolo Brigadeiro",
                            Preco = 31.50m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Bolo de Chocolate",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_chocolate.jpg",
                            Nome = "Bolo de Chocolate",
                            Preco = 41.00m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Bolo de laranja",
                            ImagemUrl = "https://macoratti.net/Imagens/bolos/bolo_laranja",
                            Nome = "Bolo de Laranja",
                            Preco = 35.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
